#pragma once

#include "mcp_manager.h"
#include "openai_client.h"
#include "types.h"
#include "util.h"
#include "variable_resolver.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <nlohmann/json.hpp>
#include <sstream>
#include <string>
#include <vector>
#include <windows.h>

namespace built_in_tools {

inline constexpr const char* kPowerShellToolName = "powershell_execute";
inline constexpr const char* kQuestionnaireToolName = "user_questionnaire";
inline constexpr const char* kPlannerToolName = "project_planner";
inline constexpr const char* kCompletionDriverToolName = "completion_driver";
inline constexpr const char* kCompletionDriverContinuationPrefix = "[Completion Driver generated continuation prompt]";
inline constexpr const char* kDefaultPlannerStorageFolder = "$ProjectFolder$\\.agent";
inline constexpr const char* kPlannerFileName = "planner.json";

inline bool IsBuiltInToolName(const std::string& name) {
    return name == kPowerShellToolName || name == kQuestionnaireToolName ||
           name == kPlannerToolName || name == kCompletionDriverToolName;
}

inline std::string TraceTitleForBuiltInTool(const std::string& name) {
    if (name == kPowerShellToolName) return "Built-in / PowerShell";
    if (name == kQuestionnaireToolName) return "Built-in / User Questionnaire";
    if (name == kPlannerToolName) return "Built-in / Planner";
    if (name == kCompletionDriverToolName) return "Built-in / Completion Driver";
    return "Built-in / " + name;
}

inline std::string LowerAsciiCopy(std::string value) {
    std::transform(value.begin(), value.end(), value.begin(),
        [](unsigned char ch) { return static_cast<char>(std::tolower(ch)); });
    return value;
}

inline bool IsQuestionnaireEnabled(const ProjectSettings& settings,
                                     const std::string& current_agentic_mode_id = {}) {
    if (!settings.built_in_questionnaire_enabled) return false;
    if (!settings.questionnaire_restrict_by_mode) return true;
    if (settings.questionnaire_allowed_mode_id.empty()) return false;
    return settings.questionnaire_allowed_mode_id == current_agentic_mode_id;
}

inline bool IsCompletionDriverEnabled(const ProjectSettings& settings,
                                       const std::string& current_agentic_mode_id = {}) {
    if (!settings.built_in_completion_driver_enabled) return false;
    if (current_agentic_mode_id.empty()) return false;
    return std::find(settings.completion_driver_allowed_mode_ids.begin(),
                     settings.completion_driver_allowed_mode_ids.end(),
                     current_agentic_mode_id) != settings.completion_driver_allowed_mode_ids.end();
}

inline std::string QuestionnaireSystemPrompt() {
    return (
        "User Questionnaire Instructions:\n"
        "- When you need a clarification, preference, or decision from the user, call the user_questionnaire tool.\n"
        "- Do NOT ask the user indirectly inside normal assistant text; always route the question through the tool.\n"
        "- Provide a concise question and a short list of distinct, actionable options.\n"
        "- After the tool returns the user's selection, use that answer to continue.\n"
        "- The tool blocks until the user responds, so the conversation will pause cleanly."
    );
}

inline std::string CompletionDriverSystemPrompt() {
    return std::string(
        "Completion Driver Instructions:\n"
        "- The Completion Driver is active for this agentic mode. The host will keep the agent running by adding driver-generated continuation prompts until you call the completion_driver tool with completed=true or status=\"completed\"/\"done\".\n"
        "- Treat any message beginning with ") + kCompletionDriverContinuationPrefix +
        " as an internal continuation prompt generated by the Completion Driver, not as a new user request.\n"
        "- Continue working across those prompts until the user's objective is fully complete.\n"
        "- When the objective is complete, call completion_driver with completed=true and a concise final_summary. After that, provide the final user-facing answer.\n"
        "- If more work remains, either keep working or call completion_driver with completed=false and remaining_work/next_action so the host can continue the loop.";
}

inline MessageRecord MakeCompletionDriverContinuationMessage(int turn_index) {
    MessageRecord message;
    message.role = "user";
    message.created_at = CurrentTimestampUtc();
    message.content = std::string(kCompletionDriverContinuationPrefix) +
        "\nThis is not a new user message. Continue the current task from the previous state. "
        "If the user's objective is now fully complete, call completion_driver with completed=true/status=completed and then provide the final answer. "
        "Otherwise continue making progress and use available tools as needed.\nContinuation turn: " +
        std::to_string(turn_index);
    return message;
}

inline bool IsCompletionDriverContinuationMessage(const MessageRecord& message) {
    return message.role == "user" &&
           message.content.rfind(kCompletionDriverContinuationPrefix, 0) == 0;
}

inline std::vector<ChatToolDefinition> BuildDefinitions(
    const ProjectSettings& settings,
    const std::string& current_agentic_mode_id = {}) {
    std::vector<ChatToolDefinition> definitions;
    if (settings.built_in_powershell_enabled) {
        ChatToolDefinition tool;
        tool.name = kPowerShellToolName;
        tool.description =
            "Execute a PowerShell command line on the host machine. This is a high-risk built-in tool: "
            "use it only when the user explicitly wants local command execution. Provide concise commands, "
            "avoid destructive actions unless explicitly requested, and report stdout/stderr back to the user.";
        tool.parameters_json = R"({
  "type": "object",
  "properties": {
    "command": {"type": "string", "description": "PowerShell command to execute."},
    "timeout_seconds": {"type": "integer", "description": "Optional timeout from 1 to 120 seconds.", "minimum": 1, "maximum": 120}
  },
  "required": ["command"]
        })";
        definitions.push_back(std::move(tool));
    }
    if (settings.built_in_planner_enabled) {
        ChatToolDefinition planner;
        planner.name = kPlannerToolName;
        planner.description =
            "Planner / Task Decomposition tool. Maintain a persistent project plan stored as planner.json in the "
            "configured project folder (default $ProjectFolder$\\.agent). Use this to track goals, subgoals, steps, "
            "features, blockers, notes, and tool hints across the full interaction.\n\n"
            "Valid actions:\n"
            "- get — Load the current plan from disk.\n"
            "- clear — Delete all items from a section (or the entire plan if section=all).\n"
            "- create or replace — Write a brand-new plan (or replace the existing one entirely). Requires 'plan'.\n"
            "- update — Merge top-level fields or sections into the existing plan. Requires 'plan'.\n"
            "- add_item — Add a new item to a section. Can be nested under a parent item.\n"
            "- update_item — Modify fields of an existing item by id (e.g. change status to completed).\n"
            "- remove_item — Delete an item by id.\n\n"
            "Sections: goals, features, steps, blockers, notes, tool_hints\n"
            "Status values (for item.status):\n"
            "- pending — Not started (unchecked in UI)\n"
            "- in_progress — Currently active (blue badge)\n"
            "- completed — Done. Checkbox checked + title struck through in UI.\n"
            "- blocked — Waiting on a blocker (red badge)\n"
            "- cancelled — Abandoned (grey badge, no strikethrough)\n\n"
            "Examples:\n"
            "1) Load plan: {\"action\":\"get\"}\n"
            "2) Create/replace full plan: {\"action\":\"create\",\"plan\":{\"goal\":\"Build app\",\"goals\":[{\"id\":\"g1\",\"title\":\"Setup\",\"status\":\"pending\"}]}}\n"
            "3) Add a top-level step: {\"action\":\"add_item\",\"section\":\"steps\",\"item\":{\"task\":\"Install deps\",\"status\":\"pending\"}}\n"
            "4) Add a nested subgoal under parent g1: {\"action\":\"add_item\",\"section\":\"goals\",\"parent_id\":\"g1\",\"item\":{\"title\":\"Subtask\",\"status\":\"pending\"}}\n"
            "5) Check off / mark completed: {\"action\":\"update_item\",\"section\":\"all\",\"id\":\"s1\",\"item\":{\"status\":\"completed\"}}\n"
            "6) Mark in progress: {\"action\":\"update_item\",\"section\":\"all\",\"id\":\"s1\",\"item\":{\"status\":\"in_progress\"}}\n"
            "7) Cancel / abandon: {\"action\":\"update_item\",\"section\":\"all\",\"id\":\"s1\",\"item\":{\"status\":\"cancelled\"}}\n"
            "8) Remove an item: {\"action\":\"remove_item\",\"section\":\"all\",\"id\":\"s1\"}\n\n"
            "Notes:\n"
            "- When adding items, an id is auto-generated if omitted.\n"
            "- child_section defaults to 'subgoals' for goals, otherwise the requested section.\n"
            "- To edit an existing item, always use update_item with the existing id.\n"
            "- The only way to get strikethrough in the UI is status=completed.\n"
            "- 'create' is an alias for 'replace' and is the preferred action when establishing a new plan.";
        planner.parameters_json = R"({
  "type": "object",
  "properties": {
    "action": {"type": "string", "enum": ["get", "create", "replace", "update", "clear", "add_item", "update_item", "remove_item"], "description": "Planner operation to perform. Use 'get' to read, 'create' or 'replace' to write a full plan, 'update' to merge fields, 'add_item' to append, 'update_item' to edit by id, 'remove_item' to delete by id, 'clear' to empty a section or all."},
    "section": {"type": "string", "enum": ["goals", "features", "steps", "blockers", "notes", "tool_hints", "all"], "description": "Plan section for item operations or section clears."},
    "id": {"description": "Item id for update_item or remove_item. String or number."},
    "parent_id": {"description": "Optional parent item id for add_item. Use this to add nested subgoals or nested steps."},
    "parent_section": {"type": "string", "enum": ["goals", "features", "steps", "blockers", "notes", "all"], "description": "Optional section to search for parent_id. Defaults to all searchable sections."},
    "child_section": {"type": "string", "enum": ["subgoals", "goals", "steps", "features", "blockers", "notes", "tool_hints"], "description": "Nested array on the parent for add_item. Defaults to subgoals when adding goals, otherwise the requested section."},
    "item": {"type": "object", "description": "Item to add or fields to merge into an existing item. Goals may include subgoals/goals and steps arrays. Steps may include nested steps. Steps should include task, status, tool_hint, and done_when when applicable."},
    "plan": {"type": "object", "description": "Complete replacement plan for create/replace, or top-level fields/sections to merge for update."}
  },
  "required": ["action"]
})";
        definitions.push_back(std::move(planner));
    }
    if (IsCompletionDriverEnabled(settings, current_agentic_mode_id)) {
        ChatToolDefinition driver;
        driver.name = kCompletionDriverToolName;
        driver.description =
            "Report whether the current user objective is complete. The host uses this built-in tool to decide "
            "whether to stop or send another Completion Driver continuation prompt. Call it with completed=true "
            "or status completed/done only when the objective is fully complete and ready for the final answer. "
            "Call it with completed=false/status continue when more work remains.";
        driver.parameters_json = R"({
  "type": "object",
  "properties": {
    "status": {"type": "string", "enum": ["continue", "completed", "done", "blocked"], "description": "Completion status for the current objective."},
    "completed": {"type": "boolean", "description": "True only when the current user objective is fully complete."},
    "final_summary": {"type": "string", "description": "Concise summary to use once complete."},
    "remaining_work": {"type": "string", "description": "What remains if the objective is not complete."},
    "next_action": {"type": "string", "description": "The next action the agent should take if continuing."}
  }
})";
        definitions.push_back(std::move(driver));
    }
    if (IsQuestionnaireEnabled(settings, current_agentic_mode_id)) {
        ChatToolDefinition q;
        q.name = kQuestionnaireToolName;
        q.description =
            "Present a multiple-choice question to the user and wait for their selection before continuing. "
            "Use this for clarifying requirements, collecting preferences, confirming trade-offs, or gathering planning decisions. "
            "The question appears as a bubble with clickable options in the web UI. The model should not assume the answer; "
            "it must wait until the user selects one of the provided choices and the tool result is injected back into context. "
            "Do not ask rhetorical questions without this tool when a decision is needed.";
        q.parameters_json = R"({"type":"object","properties":{"question":{"type":"string","description":"The question or prompt text shown to the user."},"options":{"type":"array","items":{"type":"string"},"description":"A list of distinct clickable answer choices."},"allow_multiple":{"type":"boolean","description":"If true, the user may select more than one option. Default false."}},"required":["question","options"]})";
        definitions.push_back(std::move(q));
    }
    return definitions;
}

inline std::string Base64Encode(const unsigned char* data, size_t len) {
    static constexpr char kTable[] =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    std::string out;
    out.reserve(((len + 2) / 3) * 4);
    for (size_t i = 0; i < len; i += 3) {
        const unsigned int b0 = data[i];
        const unsigned int b1 = (i + 1 < len) ? data[i + 1] : 0;
        const unsigned int b2 = (i + 2 < len) ? data[i + 2] : 0;
        out.push_back(kTable[(b0 >> 2) & 0x3F]);
        out.push_back(kTable[((b0 & 0x03) << 4) | ((b1 >> 4) & 0x0F)]);
        out.push_back(i + 1 < len ? kTable[((b1 & 0x0F) << 2) | ((b2 >> 6) & 0x03)] : '=');
        out.push_back(i + 2 < len ? kTable[b2 & 0x3F] : '=');
    }
    return out;
}

inline McpToolCallResult ErrorResult(const std::string& message) {
    McpToolCallResult result;
    result.success = false;
    result.is_tool_error = true;
    result.content_text = message;
    result.raw_result_json = nlohmann::json{{"error", message}}.dump(2);
    return result;
}

inline std::string ReadAvailablePipe(HANDLE pipe, size_t max_bytes, bool* truncated) {
    std::string output;
    char buffer[4096];
    for (;;) {
        DWORD available = 0;
        if (!PeekNamedPipe(pipe, nullptr, 0, nullptr, &available, nullptr) || available == 0) {
            break;
        }
        DWORD to_read = std::min<DWORD>(available, static_cast<DWORD>(sizeof(buffer)));
        DWORD read = 0;
        if (!ReadFile(pipe, buffer, to_read, &read, nullptr) || read == 0) {
            break;
        }
        if (output.size() + read > max_bytes) {
            const size_t remaining = max_bytes > output.size() ? max_bytes - output.size() : 0;
            output.append(buffer, buffer + remaining);
            if (truncated) *truncated = true;
        } else if (output.size() < max_bytes) {
            output.append(buffer, buffer + read);
        }
    }
    return output;
}

inline McpToolCallResult CallPowerShell(
    const std::string& arguments_json,
    const std::string& working_directory_template,
    const std::vector<ProjectMcpVariableValue>& variables) {
    nlohmann::json args;
    try {
        args = nlohmann::json::parse(arguments_json.empty() ? "{}" : arguments_json);
    } catch (const std::exception& ex) {
        return ErrorResult(std::string("Invalid PowerShell tool arguments: ") + ex.what());
    }
    const std::string command = Trim(args.value("command", ""));
    if (command.empty()) {
        return ErrorResult("PowerShell tool requires a non-empty command.");
    }
    int timeout_seconds = args.value("timeout_seconds", 30);
    timeout_seconds = std::clamp(timeout_seconds, 1, 120);

    std::string working_dir = variable_resolver::ExpandTemplate(
        working_directory_template.empty() ? "$ProjectFolder$" : working_directory_template,
        variables);
    working_dir = Trim(working_dir);

    const std::wstring command_w = Utf8ToWide(
        "[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)\n" + command);
    const std::string encoded = Base64Encode(
        reinterpret_cast<const unsigned char*>(command_w.data()),
        command_w.size() * sizeof(wchar_t));
    std::wstring command_line = L"powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -EncodedCommand " + Utf8ToWide(encoded);

    SECURITY_ATTRIBUTES sa{};
    sa.nLength = sizeof(sa);
    sa.bInheritHandle = TRUE;

    HANDLE read_pipe = nullptr;
    HANDLE write_pipe = nullptr;
    if (!CreatePipe(&read_pipe, &write_pipe, &sa, 0)) {
        return ErrorResult("Failed to create process output pipe.");
    }
    SetHandleInformation(read_pipe, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOW startup{};
    startup.cb = sizeof(startup);
    startup.dwFlags = STARTF_USESTDHANDLES;
    startup.hStdInput = nullptr;
    startup.hStdOutput = write_pipe;
    startup.hStdError = write_pipe;

    PROCESS_INFORMATION process{};
    std::vector<wchar_t> cmd_buffer(command_line.begin(), command_line.end());
    cmd_buffer.push_back(L'\0');
    std::wstring working_dir_w = Utf8ToWide(working_dir);
    const wchar_t* cwd = working_dir_w.empty() ? nullptr : working_dir_w.c_str();

    const BOOL created = CreateProcessW(
        nullptr,
        cmd_buffer.data(),
        nullptr,
        nullptr,
        TRUE,
        CREATE_NO_WINDOW,
        nullptr,
        cwd,
        &startup,
        &process);
    CloseHandle(write_pipe);
    if (!created) {
        const DWORD err = GetLastError();
        CloseHandle(read_pipe);
        return ErrorResult("Failed to start PowerShell. CreateProcess error: " + std::to_string(err));
    }

    const DWORD timeout_ms = static_cast<DWORD>(timeout_seconds) * 1000;
    const DWORD start = GetTickCount();
    bool timed_out = false;
    bool truncated = false;
    std::string output;
    constexpr size_t kMaxOutputBytes = 64 * 1024;
    for (;;) {
        output += ReadAvailablePipe(read_pipe, kMaxOutputBytes - std::min(output.size(), kMaxOutputBytes), &truncated);
        const DWORD wait = WaitForSingleObject(process.hProcess, 50);
        if (wait == WAIT_OBJECT_0) break;
        if (GetTickCount() - start >= timeout_ms) {
            timed_out = true;
            TerminateProcess(process.hProcess, 1);
            WaitForSingleObject(process.hProcess, 2000);
            break;
        }
    }
    output += ReadAvailablePipe(read_pipe, kMaxOutputBytes - std::min(output.size(), kMaxOutputBytes), &truncated);

    DWORD exit_code = 1;
    GetExitCodeProcess(process.hProcess, &exit_code);
    CloseHandle(process.hThread);
    CloseHandle(process.hProcess);
    CloseHandle(read_pipe);

    if (truncated) {
        output += "\n[output truncated at 64 KiB]";
    }

    McpToolCallResult result;
    result.success = !timed_out && exit_code == 0;
    result.is_tool_error = !result.success;
    nlohmann::json payload = {
        {"tool", kPowerShellToolName},
        {"success", result.success},
        {"exit_code", exit_code},
        {"timed_out", timed_out},
        {"working_directory", working_dir},
        {"output", output},
    };
    result.raw_result_json = payload.dump(2);
    result.content_text = "PowerShell exit code: " + std::to_string(exit_code);
    if (timed_out) result.content_text += " (timed out)";
    result.content_text += "\nWorking directory: " + (working_dir.empty() ? std::string("(default)") : working_dir);
    result.content_text += "\n\n" + (output.empty() ? std::string("(no output)") : output);
    return result;
}

inline McpToolCallResult CallQuestionnaire(
    const std::string& arguments_json,
    std::function<McpToolCallResult(const std::string&)> wait_for_answer) {
    nlohmann::json args;
    try {
        args = nlohmann::json::parse(arguments_json.empty() ? "{}" : arguments_json);
    } catch (...) {
        return ErrorResult("Invalid questionnaire tool arguments: not valid JSON.");
    }
    const std::string question = Trim(args.value("question", ""));
    const auto options_j = args.value("options", nlohmann::json::array());
    if (question.empty() || !options_j.is_array() || options_j.empty()) {
        return ErrorResult(
            "The user questionnaire tool requires a non-empty question and at least one option.");
    }
    if (wait_for_answer) {
        return wait_for_answer(arguments_json);
    }
    return ErrorResult(
        "The user questionnaire is awaiting a response from the user interface. "
        "Please wait until the user selects an option before continuing.");
}

inline McpToolCallResult CallCompletionDriver(const std::string& arguments_json) {
    nlohmann::json args;
    try {
        args = nlohmann::json::parse(arguments_json.empty() ? "{}" : arguments_json);
    } catch (const std::exception& ex) {
        return ErrorResult(std::string("Invalid completion driver arguments: ") + ex.what());
    }
    const std::string status = LowerAsciiCopy(Trim(args.value("status", "")));
    bool completed = args.value("completed", false);
    if (status == "completed" || status == "complete" || status == "done") {
        completed = true;
    }
    const std::string final_summary = Trim(args.value("final_summary", ""));
    const std::string remaining_work = Trim(args.value("remaining_work", ""));
    const std::string next_action = Trim(args.value("next_action", ""));

    McpToolCallResult result;
    result.success = true;
    nlohmann::json payload = {
        {"tool", kCompletionDriverToolName},
        {"success", true},
        {"completed", completed},
        {"status", completed ? "completed" : (status.empty() ? "continue" : status)},
        {"final_summary", final_summary},
        {"remaining_work", remaining_work},
        {"next_action", next_action},
    };
    result.raw_result_json = payload.dump(2);
    std::ostringstream text;
    text << "Completion Driver status: " << (completed ? "completed" : "continue");
    if (!final_summary.empty()) text << "\nFinal summary: " << final_summary;
    if (!remaining_work.empty()) text << "\nRemaining work: " << remaining_work;
    if (!next_action.empty()) text << "\nNext action: " << next_action;
    result.content_text = text.str();
    return result;
}

inline bool IsCompletionDriverCompletedResult(const McpToolCallResult& result) {
    try {
        const auto payload = nlohmann::json::parse(result.raw_result_json.empty() ? "{}" : result.raw_result_json);
        if (payload.value("tool", "") != kCompletionDriverToolName) return false;
        if (payload.value("completed", false)) return true;
        const std::string status = LowerAsciiCopy(Trim(payload.value("status", "")));
        return status == "completed" || status == "complete" || status == "done";
    } catch (...) {
        return false;
    }
}

inline nlohmann::json EmptyPlannerDocument() {
    return nlohmann::json{
        {"goal", ""},
        {"goals", nlohmann::json::array()},
        {"features", nlohmann::json::array()},
        {"steps", nlohmann::json::array()},
        {"blockers", nlohmann::json::array()},
        {"notes", nlohmann::json::array()},
        {"tool_hints", nlohmann::json::array({
            "web_search",
            "rag_search",
            "filesystem",
            "file_edit",
            "execution_sandbox",
            "git",
            "command_line",
            "document_parser",
        })},
        {"updated_at", CurrentTimestampUtc()},
    };
}

inline bool IsPlannerSection(const std::string& section) {
    return section == "goals" || section == "features" || section == "steps" ||
           section == "blockers" || section == "notes" || section == "tool_hints";
}

inline bool IsPlannerChildSection(const std::string& section) {
    return IsPlannerSection(section) || section == "subgoals";
}

inline std::filesystem::path PlannerFilePath(
    const ProjectSettings& settings,
    const std::vector<ProjectMcpVariableValue>& variables,
    std::string* expanded_folder_out = nullptr) {
    std::string folder_template = Trim(settings.built_in_planner_storage_folder);
    if (folder_template.empty()) {
        folder_template = kDefaultPlannerStorageFolder;
    }
    std::string expanded_folder = Trim(variable_resolver::ExpandTemplate(folder_template, variables));
    if (expanded_folder.empty()) {
        expanded_folder = kDefaultPlannerStorageFolder;
    }
    if (expanded_folder_out) {
        *expanded_folder_out = expanded_folder;
    }
    return std::filesystem::path(Utf8ToWide(expanded_folder)) / Utf8ToWide(kPlannerFileName);
}

inline bool LoadPlannerDocument(const std::filesystem::path& file_path, nlohmann::json* plan, std::string* error) {
    if (!std::filesystem::exists(file_path)) {
        *plan = EmptyPlannerDocument();
        return true;
    }
    std::ifstream input(file_path, std::ios::binary);
    if (!input.is_open()) {
        if (error) *error = "Could not open planner file for reading: " + WideToUtf8(file_path.wstring());
        return false;
    }
    try {
        input >> *plan;
    } catch (const std::exception& ex) {
        if (error) *error = std::string("Planner file is not valid JSON: ") + ex.what();
        return false;
    }
    if (!plan->is_object()) {
        if (error) *error = "Planner file root must be a JSON object.";
        return false;
    }
    return true;
}

inline bool SavePlannerDocument(const std::filesystem::path& file_path, const nlohmann::json& plan, std::string* error) {
    try {
        std::filesystem::create_directories(file_path.parent_path());
        std::ofstream output(file_path, std::ios::binary | std::ios::trunc);
        if (!output.is_open()) {
            if (error) *error = "Could not open planner file for writing: " + WideToUtf8(file_path.wstring());
            return false;
        }
        output << plan.dump(2);
        return true;
    } catch (const std::exception& ex) {
        if (error) *error = std::string("Could not save planner file: ") + ex.what();
        return false;
    }
}

inline bool PlannerIdEquals(const nlohmann::json& lhs, const nlohmann::json& rhs) {
    if (lhs == rhs) return true;
    if ((lhs.is_number_integer() || lhs.is_number_unsigned()) && rhs.is_string()) {
        return std::to_string(lhs.get<long long>()) == rhs.get<std::string>();
    }
    if (lhs.is_string() && (rhs.is_number_integer() || rhs.is_number_unsigned())) {
        return lhs.get<std::string>() == std::to_string(rhs.get<long long>());
    }
    return false;
}

inline int NextPlannerItemId(const nlohmann::json& items) {
    int next_id = 1;
    if (!items.is_array()) return next_id;
    for (const auto& item : items) {
        if (item.is_object() && item.contains("id")) {
            const auto& id = item["id"];
            if (id.is_number_integer() || id.is_number_unsigned()) {
                next_id = std::max(next_id, id.get<int>() + 1);
            }
        }
    }
    return next_id;
}

inline void UpdateMaxPlannerItemId(const nlohmann::json& items, int* max_id) {
    if (!items.is_array() || !max_id) return;
    for (const auto& item : items) {
        if (!item.is_object()) continue;
        if (item.contains("id")) {
            const auto& id = item["id"];
            if (id.is_number_integer() || id.is_number_unsigned()) {
                *max_id = std::max(*max_id, id.get<int>());
            }
        }
        for (const char* key : {"goals", "subgoals", "features", "steps", "blockers", "notes"}) {
            if (item.contains(key)) {
                UpdateMaxPlannerItemId(item[key], max_id);
            }
        }
    }
}

inline int NextPlannerItemIdInPlan(const nlohmann::json& plan) {
    int max_id = 0;
    for (const char* section : {"goals", "features", "steps", "blockers", "notes"}) {
        if (plan.contains(section)) {
            UpdateMaxPlannerItemId(plan[section], &max_id);
        }
    }
    return max_id + 1;
}

inline nlohmann::json* FindPlannerItemRecursive(nlohmann::json& items, const nlohmann::json& id) {
    if (!items.is_array()) return nullptr;
    for (auto& item : items) {
        if (!item.is_object()) continue;
        if (item.contains("id") && PlannerIdEquals(item["id"], id)) {
            return &item;
        }
        for (const char* key : {"goals", "subgoals", "features", "steps", "blockers", "notes"}) {
            if (!item.contains(key)) continue;
            if (auto* found = FindPlannerItemRecursive(item[key], id)) {
                return found;
            }
        }
    }
    return nullptr;
}

inline nlohmann::json* FindPlannerItemInPlan(
    nlohmann::json& plan,
    const nlohmann::json& id,
    const std::string& preferred_section = {}) {
    if (!preferred_section.empty() && preferred_section != "all") {
        if (!IsPlannerSection(preferred_section)) return nullptr;
        if (plan.contains(preferred_section)) {
            if (auto* found = FindPlannerItemRecursive(plan[preferred_section], id)) {
                return found;
            }
        }
    }
    for (const char* section : {"goals", "features", "steps", "blockers", "notes"}) {
        if (preferred_section == section) continue;
        if (!plan.contains(section)) continue;
        if (auto* found = FindPlannerItemRecursive(plan[section], id)) {
            return found;
        }
    }
    return nullptr;
}

inline bool RemovePlannerItemRecursive(nlohmann::json& items, const nlohmann::json& id) {
    if (!items.is_array()) return false;
    for (auto it = items.begin(); it != items.end(); ++it) {
        if (!it->is_object()) continue;
        if (it->contains("id") && PlannerIdEquals((*it)["id"], id)) {
            items.erase(it);
            return true;
        }
        for (const char* key : {"goals", "subgoals", "features", "steps", "blockers", "notes"}) {
            if (!it->contains(key)) continue;
            if (RemovePlannerItemRecursive((*it)[key], id)) {
                return true;
            }
        }
    }
    return false;
}

inline bool RemovePlannerItemFromPlan(
    nlohmann::json& plan,
    const nlohmann::json& id,
    const std::string& preferred_section = {}) {
    if (!preferred_section.empty() && preferred_section != "all") {
        if (!IsPlannerSection(preferred_section)) return false;
        if (plan.contains(preferred_section) && RemovePlannerItemRecursive(plan[preferred_section], id)) {
            return true;
        }
    }
    for (const char* section : {"goals", "features", "steps", "blockers", "notes"}) {
        if (preferred_section == section) continue;
        if (!plan.contains(section)) continue;
        if (RemovePlannerItemRecursive(plan[section], id)) {
            return true;
        }
    }
    return false;
}

inline void PreparePlannerItem(nlohmann::json& item, const std::string& section, const nlohmann::json& plan) {
    if (!item.contains("id")) {
        item["id"] = NextPlannerItemIdInPlan(plan);
    }
    if ((section == "goals" || section == "subgoals" || section == "features" ||
         section == "steps" || section == "blockers") &&
        !item.contains("status")) {
        item["status"] = "pending";
    }
}

inline McpToolCallResult PlannerResult(
    const std::string& action,
    const std::string& file_path,
    const nlohmann::json& plan,
    bool changed) {
    McpToolCallResult result;
    result.success = true;
    nlohmann::json payload = {
        {"tool", kPlannerToolName},
        {"success", true},
        {"action", action},
        {"changed", changed},
        {"path", file_path},
        {"plan", plan},
    };
    result.raw_result_json = payload.dump(2);
    result.content_text = std::string("Planner ") + (changed ? "updated" : "loaded") + ".\nPath: " + file_path + "\n\n" + plan.dump(2);
    return result;
}

inline McpToolCallResult CallPlanner(
    const std::string& arguments_json,
    const ProjectSettings& settings,
    const std::vector<ProjectMcpVariableValue>& variables) {
    nlohmann::json args;
    try {
        args = nlohmann::json::parse(arguments_json.empty() ? "{}" : arguments_json);
    } catch (const std::exception& ex) {
        return ErrorResult(std::string("Invalid planner tool arguments: ") + ex.what());
    }
    const std::string action = Trim(args.value("action", ""));
    if (action.empty()) {
        return ErrorResult("Planner tool requires an action.");
    }

    std::string expanded_folder;
    const std::filesystem::path file_path = PlannerFilePath(settings, variables, &expanded_folder);
    const std::string file_path_utf8 = WideToUtf8(file_path.wstring());

    nlohmann::json plan;
    std::string error;
    if (!LoadPlannerDocument(file_path, &plan, &error)) {
        return ErrorResult(error);
    }

    bool changed = false;
    if (action == "get") {
        return PlannerResult(action, file_path_utf8, plan, false);
    }
    if (action == "clear") {
        const std::string section = Trim(args.value("section", "all"));
        if (section.empty() || section == "all") {
            plan = EmptyPlannerDocument();
        } else {
            if (!IsPlannerSection(section)) return ErrorResult("Invalid planner section: " + section);
            plan[section] = nlohmann::json::array();
        }
        changed = true;
    } else if (action == "create" || action == "replace") {
        if (!args.contains("plan") || !args["plan"].is_object()) {
            return ErrorResult("Planner create/replace requires a plan object.");
        }
        plan = args["plan"];
        changed = true;
    } else if (action == "update") {
        if (!args.contains("plan") || !args["plan"].is_object()) {
            return ErrorResult("Planner update requires a plan object.");
        }
        for (auto it = args["plan"].begin(); it != args["plan"].end(); ++it) {
            plan[it.key()] = it.value();
        }
        changed = true;
    } else if (action == "add_item") {
        const std::string section = Trim(args.value("section", "steps"));
        if (!IsPlannerSection(section) || section == "all") return ErrorResult("Invalid planner section: " + section);
        if (!args.contains("item") || !args["item"].is_object()) {
            return ErrorResult("Planner add_item requires an item object.");
        }
        nlohmann::json item = args["item"];
        if (args.contains("parent_id")) {
            const std::string parent_section = Trim(args.value("parent_section", "all"));
            if (!parent_section.empty() && parent_section != "all" && !IsPlannerSection(parent_section)) {
                return ErrorResult("Invalid planner parent_section: " + parent_section);
            }
            nlohmann::json* parent = FindPlannerItemInPlan(plan, args["parent_id"], parent_section);
            if (!parent) {
                return ErrorResult("Planner parent item not found.");
            }
            std::string child_section = Trim(args.value("child_section", ""));
            if (child_section.empty()) {
                child_section = section == "goals" ? "subgoals" : section;
            }
            if (!IsPlannerChildSection(child_section)) {
                return ErrorResult("Invalid planner child_section: " + child_section);
            }
            if (!parent->contains(child_section) || !(*parent)[child_section].is_array()) {
                (*parent)[child_section] = nlohmann::json::array();
            }
            PreparePlannerItem(item, child_section, plan);
            (*parent)[child_section].push_back(std::move(item));
        } else {
            if (!plan.contains(section) || !plan[section].is_array()) {
                plan[section] = nlohmann::json::array();
            }
            PreparePlannerItem(item, section, plan);
            plan[section].push_back(std::move(item));
        }
        changed = true;
    } else if (action == "update_item" || action == "remove_item") {
        const std::string section = Trim(args.value("section", "steps"));
        if (section != "all" && !IsPlannerSection(section)) return ErrorResult("Invalid planner section: " + section);
        if (!args.contains("id")) return ErrorResult("Planner " + action + " requires an id.");
        if (action == "remove_item") {
            if (!RemovePlannerItemFromPlan(plan, args["id"], section)) {
                return ErrorResult("Planner item not found in section " + section + ".");
            }
            changed = true;
        } else {
            nlohmann::json* item = FindPlannerItemInPlan(plan, args["id"], section);
            if (!item) return ErrorResult("Planner item not found in section " + section + ".");
            if (!args.contains("item") || !args["item"].is_object()) {
                return ErrorResult("Planner update_item requires an item object with fields to update.");
            }
            for (auto field = args["item"].begin(); field != args["item"].end(); ++field) {
                (*item)[field.key()] = field.value();
            }
            changed = true;
        }
    } else {
        return ErrorResult("Unknown planner action: " + action);
    }

    if (changed) {
        plan["updated_at"] = CurrentTimestampUtc();
        if (!SavePlannerDocument(file_path, plan, &error)) {
            return ErrorResult(error);
        }
    }
    return PlannerResult(action, file_path_utf8, plan, changed);
}

inline McpToolCallResult CallTool(
    const std::string& name,
    const std::string& arguments_json,
    const ProjectSettings& settings,
    const std::vector<ProjectMcpVariableValue>& variables,
    const std::string& current_agentic_mode_id = {},
    std::function<McpToolCallResult(const std::string&)> questionnaire_wait = {}) {
    if (name == kPowerShellToolName && settings.built_in_powershell_enabled) {
        return CallPowerShell(arguments_json, settings.built_in_powershell_working_directory, variables);
    }
    if (name == kPlannerToolName && settings.built_in_planner_enabled) {
        return CallPlanner(arguments_json, settings, variables);
    }
    if (name == kCompletionDriverToolName && IsCompletionDriverEnabled(settings, current_agentic_mode_id)) {
        return CallCompletionDriver(arguments_json);
    }
    if (name == kQuestionnaireToolName && IsQuestionnaireEnabled(settings, current_agentic_mode_id)) {
        return CallQuestionnaire(arguments_json, questionnaire_wait);
    }
    return ErrorResult("Built-in tool is not enabled for this project: " + name);
}

}  // namespace built_in_tools
